import {ISeeder} from '../interfaces/seeder.interface';
import {MasterDataSource} from '../datasource';
import {Country} from '../../master/countries/entities';
import {State} from '../../master/states/entities';

export class StateSeeder implements ISeeder {
  name = 'StateSeeder';

  async run() {
    const countryRepo = MasterDataSource.getRepository(Country);
    const stateRepo = MasterDataSource.getRepository(State);

    if (await stateRepo.count()) {
      console.log('⚠️  States already exist. Skipping seeding.');
      return;
    }

    const countries = await countryRepo.find();
    if (!countries.length) {
      console.log('⚠️  Countries are missing. Run CountrySeeder first.');
      return;
    }

    const byCode = new Map(countries.map((country) => [country.code, country]));

    const rows: Array<{name: string; code: string}> = [
      // Afghanistan
      {name: 'Kabul', code: 'AF'},
      {name: 'Kandahar', code: 'AF'},
      {name: 'Herat', code: 'AF'},
      {name: 'Balkh', code: 'AF'},
      {name: 'Nangarhar', code: 'AF'},
      {name: 'Kunduz', code: 'AF'},
      // Albania
      {name: 'Tirana', code: 'AL'},
      {name: 'Durrës', code: 'AL'},
      {name: 'Vlorë', code: 'AL'},
      // Algeria
      {name: 'Algiers', code: 'DZ'},
      {name: 'Oran', code: 'DZ'},
      {name: 'Constantine', code: 'DZ'},
      {name: 'Annaba', code: 'DZ'},
      // Argentina
      {name: 'Buenos Aires', code: 'AR'},
      {name: 'Córdoba', code: 'AR'},
      {name: 'Santa Fe', code: 'AR'},
      {name: 'Mendoza', code: 'AR'},
      {name: 'Tucumán', code: 'AR'},
      {name: 'Salta', code: 'AR'},
      // Australia
      {name: 'New South Wales', code: 'AU'},
      {name: 'Victoria', code: 'AU'},
      {name: 'Queensland', code: 'AU'},
      {name: 'Western Australia', code: 'AU'},
      {name: 'South Australia', code: 'AU'},
      {name: 'Tasmania', code: 'AU'},
      {name: 'Australian Capital Territory', code: 'AU'},
      {name: 'Northern Territory', code: 'AU'},
      // Austria
      {name: 'Vienna', code: 'AT'},
      {name: 'Lower Austria', code: 'AT'},
      {name: 'Upper Austria', code: 'AT'},
      {name: 'Styria', code: 'AT'},
      {name: 'Tyrol', code: 'AT'},
      {name: 'Salzburg', code: 'AT'},
      {name: 'Carinthia', code: 'AT'},
      {name: 'Vorarlberg', code: 'AT'},
      {name: 'Burgenland', code: 'AT'},
      // Azerbaijan
      {name: 'Baku', code: 'AZ'},
      {name: 'Ganja', code: 'AZ'},
      {name: 'Sumqayit', code: 'AZ'},
      // Bahrain
      {name: 'Capital Governorate', code: 'BH'},
      {name: 'Muharraq Governorate', code: 'BH'},
      {name: 'Northern Governorate', code: 'BH'},
      {name: 'Southern Governorate', code: 'BH'},
      // Bangladesh
      {name: 'Dhaka', code: 'BD'},
      {name: 'Chittagong', code: 'BD'},
      {name: 'Rajshahi', code: 'BD'},
      {name: 'Khulna', code: 'BD'},
      {name: 'Sylhet', code: 'BD'},
      {name: 'Barisal', code: 'BD'},
      {name: 'Rangpur', code: 'BD'},
      {name: 'Mymensingh', code: 'BD'},
      // Belgium
      {name: 'Brussels', code: 'BE'},
      {name: 'Flanders', code: 'BE'},
      {name: 'Wallonia', code: 'BE'},
      // Brazil
      {name: 'São Paulo', code: 'BR'},
      {name: 'Rio de Janeiro', code: 'BR'},
      {name: 'Minas Gerais', code: 'BR'},
      {name: 'Bahia', code: 'BR'},
      {name: 'Rio Grande do Sul', code: 'BR'},
      {name: 'Paraná', code: 'BR'},
      {name: 'Pernambuco', code: 'BR'},
      {name: 'Ceará', code: 'BR'},
      {name: 'Pará', code: 'BR'},
      {name: 'Amazonas', code: 'BR'},
      {name: 'Goiás', code: 'BR'},
      {name: 'Maranhão', code: 'BR'},
      {name: 'Santa Catarina', code: 'BR'},
      {name: 'Mato Grosso', code: 'BR'},
      {name: 'Espírito Santo', code: 'BR'},
      {name: 'Alagoas', code: 'BR'},
      {name: 'Piauí', code: 'BR'},
      {name: 'Mato Grosso do Sul', code: 'BR'},
      {name: 'Rio Grande do Norte', code: 'BR'},
      {name: 'Sergipe', code: 'BR'},
      {name: 'Tocantins', code: 'BR'},
      {name: 'Rondônia', code: 'BR'},
      {name: 'Roraima', code: 'BR'},
      {name: 'Acre', code: 'BR'},
      {name: 'Amapá', code: 'BR'},
      {name: 'Paraíba', code: 'BR'},
      {name: 'Distrito Federal', code: 'BR'},
      // Canada
      {name: 'Ontario', code: 'CA'},
      {name: 'Quebec', code: 'CA'},
      {name: 'British Columbia', code: 'CA'},
      {name: 'Alberta', code: 'CA'},
      {name: 'Manitoba', code: 'CA'},
      {name: 'Saskatchewan', code: 'CA'},
      {name: 'Nova Scotia', code: 'CA'},
      {name: 'New Brunswick', code: 'CA'},
      {name: 'Newfoundland and Labrador', code: 'CA'},
      {name: 'Prince Edward Island', code: 'CA'},
      {name: 'Northwest Territories', code: 'CA'},
      {name: 'Yukon', code: 'CA'},
      {name: 'Nunavut', code: 'CA'},
      // Chile
      {name: 'Santiago Metropolitan', code: 'CL'},
      {name: 'Valparaíso', code: 'CL'},
      {name: 'Biobío', code: 'CL'},
      {name: 'Maule', code: 'CL'},
      {name: 'La Araucanía', code: 'CL'},
      // China
      {name: 'Beijing', code: 'CN'},
      {name: 'Shanghai', code: 'CN'},
      {name: 'Guangdong', code: 'CN'},
      {name: 'Sichuan', code: 'CN'},
      {name: 'Henan', code: 'CN'},
      {name: 'Shandong', code: 'CN'},
      {name: 'Jiangsu', code: 'CN'},
      {name: 'Zhejiang', code: 'CN'},
      {name: 'Hubei', code: 'CN'},
      {name: 'Hunan', code: 'CN'},
      {name: 'Fujian', code: 'CN'},
      {name: 'Shaanxi', code: 'CN'},
      {name: 'Liaoning', code: 'CN'},
      {name: 'Yunnan', code: 'CN'},
      {name: 'Jilin', code: 'CN'},
      {name: 'Heilongjiang', code: 'CN'},
      {name: 'Shanxi', code: 'CN'},
      {name: 'Guizhou', code: 'CN'},
      {name: 'Jiangxi', code: 'CN'},
      {name: 'Tianjin', code: 'CN'},
      {name: 'Chongqing', code: 'CN'},
      {name: 'Xinjiang', code: 'CN'},
      {name: 'Tibet', code: 'CN'},
      {name: 'Guangxi', code: 'CN'},
      {name: 'Inner Mongolia', code: 'CN'},
      // Colombia
      {name: 'Bogotá', code: 'CO'},
      {name: 'Antioquia', code: 'CO'},
      {name: 'Valle del Cauca', code: 'CO'},
      {name: 'Cundinamarca', code: 'CO'},
      {name: 'Santander', code: 'CO'},
      // Czech Republic
      {name: 'Prague', code: 'CZ'},
      {name: 'South Moravian', code: 'CZ'},
      {name: 'Moravia-Silesia', code: 'CZ'},
      {name: 'Central Bohemian', code: 'CZ'},
      // Denmark
      {name: 'Capital Region', code: 'DK'},
      {name: 'Central Denmark', code: 'DK'},
      {name: 'North Denmark', code: 'DK'},
      {name: 'Southern Denmark', code: 'DK'},
      {name: 'Zealand', code: 'DK'},
      // Egypt
      {name: 'Cairo', code: 'EG'},
      {name: 'Giza', code: 'EG'},
      {name: 'Alexandria', code: 'EG'},
      {name: 'Dakahlia', code: 'EG'},
      {name: 'Beheira', code: 'EG'},
      {name: 'Gharbia', code: 'EG'},
      {name: 'Sharqia', code: 'EG'},
      {name: 'Qalyubia', code: 'EG'},
      {name: 'Luxor', code: 'EG'},
      {name: 'Aswan', code: 'EG'},
      // Ethiopia
      {name: 'Addis Ababa', code: 'ET'},
      {name: 'Oromia', code: 'ET'},
      {name: 'Amhara', code: 'ET'},
      {name: 'Tigray', code: 'ET'},
      {name: 'Somali', code: 'ET'},
      // France
      {name: 'Île-de-France', code: 'FR'},
      {name: 'Auvergne-Rhône-Alpes', code: 'FR'},
      {name: 'Nouvelle-Aquitaine', code: 'FR'},
      {name: 'Occitanie', code: 'FR'},
      {name: 'Hauts-de-France', code: 'FR'},
      {name: 'Grand Est', code: 'FR'},
      {name: 'Provence-Alpes-Côte d\'Azur', code: 'FR'},
      {name: 'Pays de la Loire', code: 'FR'},
      {name: 'Normandie', code: 'FR'},
      {name: 'Bretagne', code: 'FR'},
      {name: 'Bourgogne-Franche-Comté', code: 'FR'},
      {name: 'Centre-Val de Loire', code: 'FR'},
      {name: 'Corse', code: 'FR'},
      // Germany
      {name: 'Bavaria', code: 'DE'},
      {name: 'North Rhine-Westphalia', code: 'DE'},
      {name: 'Baden-Württemberg', code: 'DE'},
      {name: 'Lower Saxony', code: 'DE'},
      {name: 'Hesse', code: 'DE'},
      {name: 'Saxony', code: 'DE'},
      {name: 'Rhineland-Palatinate', code: 'DE'},
      {name: 'Berlin', code: 'DE'},
      {name: 'Schleswig-Holstein', code: 'DE'},
      {name: 'Brandenburg', code: 'DE'},
      {name: 'Saxony-Anhalt', code: 'DE'},
      {name: 'Thuringia', code: 'DE'},
      {name: 'Hamburg', code: 'DE'},
      {name: 'Mecklenburg-Vorpommern', code: 'DE'},
      {name: 'Saarland', code: 'DE'},
      {name: 'Bremen', code: 'DE'},
      // Ghana
      {name: 'Greater Accra', code: 'GH'},
      {name: 'Ashanti', code: 'GH'},
      {name: 'Western', code: 'GH'},
      {name: 'Eastern', code: 'GH'},
      {name: 'Northern', code: 'GH'},
      // India
      {name: 'Uttar Pradesh', code: 'IN'},
      {name: 'Maharashtra', code: 'IN'},
      {name: 'Bihar', code: 'IN'},
      {name: 'West Bengal', code: 'IN'},
      {name: 'Madhya Pradesh', code: 'IN'},
      {name: 'Tamil Nadu', code: 'IN'},
      {name: 'Rajasthan', code: 'IN'},
      {name: 'Karnataka', code: 'IN'},
      {name: 'Gujarat', code: 'IN'},
      {name: 'Andhra Pradesh', code: 'IN'},
      {name: 'Odisha', code: 'IN'},
      {name: 'Telangana', code: 'IN'},
      {name: 'Kerala', code: 'IN'},
      {name: 'Jharkhand', code: 'IN'},
      {name: 'Assam', code: 'IN'},
      {name: 'Punjab', code: 'IN'},
      {name: 'Chhattisgarh', code: 'IN'},
      {name: 'Haryana', code: 'IN'},
      {name: 'Delhi', code: 'IN'},
      {name: 'Uttarakhand', code: 'IN'},
      {name: 'Himachal Pradesh', code: 'IN'},
      {name: 'Tripura', code: 'IN'},
      {name: 'Meghalaya', code: 'IN'},
      {name: 'Manipur', code: 'IN'},
      {name: 'Nagaland', code: 'IN'},
      {name: 'Goa', code: 'IN'},
      {name: 'Arunachal Pradesh', code: 'IN'},
      {name: 'Mizoram', code: 'IN'},
      {name: 'Sikkim', code: 'IN'},
      // Indonesia
      {name: 'Java', code: 'ID'},
      {name: 'Sumatra', code: 'ID'},
      {name: 'Kalimantan', code: 'ID'},
      {name: 'Sulawesi', code: 'ID'},
      {name: 'Papua', code: 'ID'},
      {name: 'Bali', code: 'ID'},
      {name: 'West Nusa Tenggara', code: 'ID'},
      {name: 'East Nusa Tenggara', code: 'ID'},
      // Iran
      {name: 'Tehran', code: 'IR'},
      {name: 'Isfahan', code: 'IR'},
      {name: 'Razavi Khorasan', code: 'IR'},
      {name: 'Fars', code: 'IR'},
      {name: 'Khuzestan', code: 'IR'},
      {name: 'East Azerbaijan', code: 'IR'},
      {name: 'Mazandaran', code: 'IR'},
      {name: 'Gilan', code: 'IR'},
      // Iraq
      {name: 'Baghdad', code: 'IQ'},
      {name: 'Basra', code: 'IQ'},
      {name: 'Nineveh', code: 'IQ'},
      {name: 'Erbil', code: 'IQ'},
      {name: 'Sulaymaniyah', code: 'IQ'},
      {name: 'Diyala', code: 'IQ'},
      {name: 'Kirkuk', code: 'IQ'},
      // Italy
      {name: 'Lombardy', code: 'IT'},
      {name: 'Lazio', code: 'IT'},
      {name: 'Campania', code: 'IT'},
      {name: 'Sicily', code: 'IT'},
      {name: 'Veneto', code: 'IT'},
      {name: 'Piedmont', code: 'IT'},
      {name: 'Emilia-Romagna', code: 'IT'},
      {name: 'Puglia', code: 'IT'},
      {name: 'Tuscany', code: 'IT'},
      {name: 'Calabria', code: 'IT'},
      {name: 'Sardinia', code: 'IT'},
      // Japan
      {name: 'Tokyo', code: 'JP'},
      {name: 'Osaka', code: 'JP'},
      {name: 'Kanagawa', code: 'JP'},
      {name: 'Aichi', code: 'JP'},
      {name: 'Saitama', code: 'JP'},
      {name: 'Chiba', code: 'JP'},
      {name: 'Hokkaido', code: 'JP'},
      {name: 'Hyogo', code: 'JP'},
      {name: 'Fukuoka', code: 'JP'},
      {name: 'Shizuoka', code: 'JP'},
      {name: 'Kyoto', code: 'JP'},
      {name: 'Nara', code: 'JP'},
      {name: 'Hiroshima', code: 'JP'},
      {name: 'Okinawa', code: 'JP'},
      // Jordan
      {name: 'Amman', code: 'JO'},
      {name: 'Zarqa', code: 'JO'},
      {name: 'Irbid', code: 'JO'},
      {name: 'Aqaba', code: 'JO'},
      // Kenya
      {name: 'Nairobi', code: 'KE'},
      {name: 'Mombasa', code: 'KE'},
      {name: 'Kisumu', code: 'KE'},
      {name: 'Nakuru', code: 'KE'},
      {name: 'Eldoret', code: 'KE'},
      // Kuwait
      {name: 'Al Asimah', code: 'KW'},
      {name: 'Hawalli', code: 'KW'},
      {name: 'Ahmadi', code: 'KW'},
      {name: 'Mubarak Al-Kabeer', code: 'KW'},
      {name: 'Farwaniya', code: 'KW'},
      {name: 'Jahra', code: 'KW'},
      // Malaysia
      {name: 'Selangor', code: 'MY'},
      {name: 'Johor', code: 'MY'},
      {name: 'Perak', code: 'MY'},
      {name: 'Sabah', code: 'MY'},
      {name: 'Sarawak', code: 'MY'},
      {name: 'Penang', code: 'MY'},
      {name: 'Kelantan', code: 'MY'},
      {name: 'Terengganu', code: 'MY'},
      {name: 'Kedah', code: 'MY'},
      {name: 'Kuala Lumpur', code: 'MY'},
      {name: 'Pahang', code: 'MY'},
      {name: 'Negeri Sembilan', code: 'MY'},
      {name: 'Malacca', code: 'MY'},
      {name: 'Perlis', code: 'MY'},
      // Mexico
      {name: 'Mexico City', code: 'MX'},
      {name: 'State of Mexico', code: 'MX'},
      {name: 'Jalisco', code: 'MX'},
      {name: 'Nuevo León', code: 'MX'},
      {name: 'Guanajuato', code: 'MX'},
      {name: 'Chihuahua', code: 'MX'},
      {name: 'Veracruz', code: 'MX'},
      {name: 'Puebla', code: 'MX'},
      {name: 'Michoacán', code: 'MX'},
      {name: 'Oaxaca', code: 'MX'},
      {name: 'Guerrero', code: 'MX'},
      {name: 'Baja California', code: 'MX'},
      {name: 'Sonora', code: 'MX'},
      {name: 'Tamaulipas', code: 'MX'},
      {name: 'Sinaloa', code: 'MX'},
      {name: 'Coahuila', code: 'MX'},
      {name: 'Hidalgo', code: 'MX'},
      {name: 'San Luis Potosí', code: 'MX'},
      {name: 'Chiapas', code: 'MX'},
      {name: 'Tabasco', code: 'MX'},
      // Morocco
      {name: 'Casablanca-Settat', code: 'MA'},
      {name: 'Rabat-Salé-Kénitra', code: 'MA'},
      {name: 'Marrakesh-Safi', code: 'MA'},
      {name: 'Fès-Meknès', code: 'MA'},
      {name: 'Tanger-Tétouan-Al Hoceïma', code: 'MA'},
      // Nigeria
      {name: 'Lagos', code: 'NG'},
      {name: 'Kano', code: 'NG'},
      {name: 'Rivers', code: 'NG'},
      {name: 'Oyo', code: 'NG'},
      {name: 'FCT Abuja', code: 'NG'},
      {name: 'Kaduna', code: 'NG'},
      {name: 'Delta', code: 'NG'},
      {name: 'Anambra', code: 'NG'},
      {name: 'Enugu', code: 'NG'},
      {name: 'Imo', code: 'NG'},
      {name: 'Kwara', code: 'NG'},
      {name: 'Ondo', code: 'NG'},
      {name: 'Edo', code: 'NG'},
      {name: 'Osun', code: 'NG'},
      // Norway
      {name: 'Oslo', code: 'NO'},
      {name: 'Viken', code: 'NO'},
      {name: 'Innlandet', code: 'NO'},
      {name: 'Vestland', code: 'NO'},
      {name: 'Trøndelag', code: 'NO'},
      // Oman
      {name: 'Muscat', code: 'OM'},
      {name: 'Dhofar', code: 'OM'},
      {name: 'Al Batinah North', code: 'OM'},
      {name: 'Al Batinah South', code: 'OM'},
      {name: 'Ad Dakhiliyah', code: 'OM'},
      {name: 'Ash Sharqiyah North', code: 'OM'},
      {name: 'Ash Sharqiyah South', code: 'OM'},
      {name: 'Al Buraymi', code: 'OM'},
      // Pakistan
      {name: 'Punjab', code: 'PK'},
      {name: 'Sindh', code: 'PK'},
      {name: 'Khyber Pakhtunkhwa', code: 'PK'},
      {name: 'Balochistan', code: 'PK'},
      {name: 'Islamabad Capital Territory', code: 'PK'},
      {name: 'Gilgit-Baltistan', code: 'PK'},
      {name: 'Azad Kashmir', code: 'PK'},
      // Philippines
      {name: 'Metro Manila', code: 'PH'},
      {name: 'Calabarzon', code: 'PH'},
      {name: 'Central Luzon', code: 'PH'},
      {name: 'Western Visayas', code: 'PH'},
      {name: 'Central Visayas', code: 'PH'},
      {name: 'Davao Region', code: 'PH'},
      {name: 'Ilocos Region', code: 'PH'},
      {name: 'Bicol Region', code: 'PH'},
      {name: 'Northern Mindanao', code: 'PH'},
      {name: 'Zamboanga Peninsula', code: 'PH'},
      // Poland
      {name: 'Masovian', code: 'PL'},
      {name: 'Silesian', code: 'PL'},
      {name: 'Lesser Poland', code: 'PL'},
      {name: 'Greater Poland', code: 'PL'},
      {name: 'Lower Silesian', code: 'PL'},
      {name: 'Łódź', code: 'PL'},
      {name: 'Pomeranian', code: 'PL'},
      {name: 'Kuyavian-Pomeranian', code: 'PL'},
      {name: 'Lublin', code: 'PL'},
      // Portugal
      {name: 'Lisbon', code: 'PT'},
      {name: 'Porto', code: 'PT'},
      {name: 'Braga', code: 'PT'},
      {name: 'Setúbal', code: 'PT'},
      {name: 'Aveiro', code: 'PT'},
      // Qatar
      {name: 'Doha', code: 'QA'},
      {name: 'Al Rayyan', code: 'QA'},
      {name: 'Al Wakrah', code: 'QA'},
      {name: 'Al Khor', code: 'QA'},
      {name: 'Al Shamal', code: 'QA'},
      {name: 'Umm Salal', code: 'QA'},
      {name: 'Al Daayen', code: 'QA'},
      {name: 'Al Shahaniya', code: 'QA'},
      // Romania
      {name: 'Bucharest', code: 'RO'},
      {name: 'Cluj', code: 'RO'},
      {name: 'Iași', code: 'RO'},
      {name: 'Constanța', code: 'RO'},
      {name: 'Timiș', code: 'RO'},
      // Russia
      {name: 'Moscow', code: 'RU'},
      {name: 'Saint Petersburg', code: 'RU'},
      {name: 'Krasnodar Krai', code: 'RU'},
      {name: 'Sverdlovsk Oblast', code: 'RU'},
      {name: 'Novosibirsk Oblast', code: 'RU'},
      {name: 'Tatarstan', code: 'RU'},
      {name: 'Chelyabinsk Oblast', code: 'RU'},
      {name: 'Samara Oblast', code: 'RU'},
      {name: 'Bashkortostan', code: 'RU'},
      {name: 'Nizhny Novgorod Oblast', code: 'RU'},
      // Saudi Arabia
      {name: 'Riyadh', code: 'SA'},
      {name: 'Makkah', code: 'SA'},
      {name: 'Madinah', code: 'SA'},
      {name: 'Eastern Province', code: 'SA'},
      {name: 'Asir', code: 'SA'},
      {name: 'Tabuk', code: 'SA'},
      {name: 'Hail', code: 'SA'},
      {name: 'Jizan', code: 'SA'},
      {name: 'Al Qassim', code: 'SA'},
      {name: 'Al-Jawf', code: 'SA'},
      {name: 'Najran', code: 'SA'},
      {name: 'Al Bahah', code: 'SA'},
      {name: 'Northern Borders', code: 'SA'},
      // South Africa
      {name: 'Gauteng', code: 'ZA'},
      {name: 'Western Cape', code: 'ZA'},
      {name: 'KwaZulu-Natal', code: 'ZA'},
      {name: 'Eastern Cape', code: 'ZA'},
      {name: 'Limpopo', code: 'ZA'},
      {name: 'Mpumalanga', code: 'ZA'},
      {name: 'North West', code: 'ZA'},
      {name: 'Free State', code: 'ZA'},
      {name: 'Northern Cape', code: 'ZA'},
      // South Korea
      {name: 'Seoul', code: 'KR'},
      {name: 'Gyeonggi', code: 'KR'},
      {name: 'Busan', code: 'KR'},
      {name: 'Incheon', code: 'KR'},
      {name: 'Daegu', code: 'KR'},
      {name: 'Daejeon', code: 'KR'},
      {name: 'Gwangju', code: 'KR'},
      {name: 'Ulsan', code: 'KR'},
      {name: 'Sejong', code: 'KR'},
      // Spain
      {name: 'Catalonia', code: 'ES'},
      {name: 'Andalusia', code: 'ES'},
      {name: 'Community of Madrid', code: 'ES'},
      {name: 'Valencia', code: 'ES'},
      {name: 'Galicia', code: 'ES'},
      {name: 'Castile and León', code: 'ES'},
      {name: 'Basque Country', code: 'ES'},
      {name: 'Castilla-La Mancha', code: 'ES'},
      {name: 'Canary Islands', code: 'ES'},
      {name: 'Murcia', code: 'ES'},
      {name: 'Aragon', code: 'ES'},
      {name: 'Extremadura', code: 'ES'},
      {name: 'Balearic Islands', code: 'ES'},
      {name: 'Asturias', code: 'ES'},
      {name: 'Navarre', code: 'ES'},
      {name: 'Cantabria', code: 'ES'},
      {name: 'La Rioja', code: 'ES'},
      // Sweden
      {name: 'Stockholm', code: 'SE'},
      {name: 'Västra Götaland', code: 'SE'},
      {name: 'Skåne', code: 'SE'},
      {name: 'Uppsala', code: 'SE'},
      {name: 'Östergötland', code: 'SE'},
      // Switzerland
      {name: 'Zurich', code: 'CH'},
      {name: 'Bern', code: 'CH'},
      {name: 'Vaud', code: 'CH'},
      {name: 'Geneva', code: 'CH'},
      {name: 'Basel-City', code: 'CH'},
      {name: 'Aargau', code: 'CH'},
      {name: 'Ticino', code: 'CH'},
      // Turkey
      {name: 'Istanbul', code: 'TR'},
      {name: 'Ankara', code: 'TR'},
      {name: 'Izmir', code: 'TR'},
      {name: 'Bursa', code: 'TR'},
      {name: 'Antalya', code: 'TR'},
      {name: 'Adana', code: 'TR'},
      {name: 'Konya', code: 'TR'},
      {name: 'Gaziantep', code: 'TR'},
      {name: 'Mersin', code: 'TR'},
      {name: 'Kayseri', code: 'TR'},
      // Ukraine
      {name: 'Kyiv', code: 'UA'},
      {name: 'Kharkiv', code: 'UA'},
      {name: 'Dnipropetrovsk', code: 'UA'},
      {name: 'Donetsk', code: 'UA'},
      {name: 'Zaporizhzhia', code: 'UA'},
      {name: 'Lviv', code: 'UA'},
      {name: 'Odessa', code: 'UA'},
      // United Arab Emirates
      {name: 'Abu Dhabi', code: 'AE'},
      {name: 'Dubai', code: 'AE'},
      {name: 'Sharjah', code: 'AE'},
      {name: 'Ajman', code: 'AE'},
      {name: 'Ras Al Khaimah', code: 'AE'},
      {name: 'Fujairah', code: 'AE'},
      {name: 'Umm Al Quwain', code: 'AE'},
      // United Kingdom
      {name: 'England', code: 'GB'},
      {name: 'Scotland', code: 'GB'},
      {name: 'Wales', code: 'GB'},
      {name: 'Northern Ireland', code: 'GB'},
      // United States
      {name: 'Alabama', code: 'US'},
      {name: 'Alaska', code: 'US'},
      {name: 'Arizona', code: 'US'},
      {name: 'Arkansas', code: 'US'},
      {name: 'California', code: 'US'},
      {name: 'Colorado', code: 'US'},
      {name: 'Connecticut', code: 'US'},
      {name: 'Delaware', code: 'US'},
      {name: 'Florida', code: 'US'},
      {name: 'Georgia', code: 'US'},
      {name: 'Hawaii', code: 'US'},
      {name: 'Idaho', code: 'US'},
      {name: 'Illinois', code: 'US'},
      {name: 'Indiana', code: 'US'},
      {name: 'Iowa', code: 'US'},
      {name: 'Kansas', code: 'US'},
      {name: 'Kentucky', code: 'US'},
      {name: 'Louisiana', code: 'US'},
      {name: 'Maine', code: 'US'},
      {name: 'Maryland', code: 'US'},
      {name: 'Massachusetts', code: 'US'},
      {name: 'Michigan', code: 'US'},
      {name: 'Minnesota', code: 'US'},
      {name: 'Mississippi', code: 'US'},
      {name: 'Missouri', code: 'US'},
      {name: 'Montana', code: 'US'},
      {name: 'Nebraska', code: 'US'},
      {name: 'Nevada', code: 'US'},
      {name: 'New Hampshire', code: 'US'},
      {name: 'New Jersey', code: 'US'},
      {name: 'New Mexico', code: 'US'},
      {name: 'New York', code: 'US'},
      {name: 'North Carolina', code: 'US'},
      {name: 'North Dakota', code: 'US'},
      {name: 'Ohio', code: 'US'},
      {name: 'Oklahoma', code: 'US'},
      {name: 'Oregon', code: 'US'},
      {name: 'Pennsylvania', code: 'US'},
      {name: 'Rhode Island', code: 'US'},
      {name: 'South Carolina', code: 'US'},
      {name: 'South Dakota', code: 'US'},
      {name: 'Tennessee', code: 'US'},
      {name: 'Texas', code: 'US'},
      {name: 'Utah', code: 'US'},
      {name: 'Vermont', code: 'US'},
      {name: 'Virginia', code: 'US'},
      {name: 'Washington', code: 'US'},
      {name: 'West Virginia', code: 'US'},
      {name: 'Wisconsin', code: 'US'},
      {name: 'Wyoming', code: 'US'},
      {name: 'District of Columbia', code: 'US'},
      // Venezuela
      {name: 'Capital District', code: 'VE'},
      {name: 'Miranda', code: 'VE'},
      {name: 'Zulia', code: 'VE'},
      {name: 'Carabobo', code: 'VE'},
      {name: 'Aragua', code: 'VE'},
      // Vietnam
      {name: 'Hanoi', code: 'VN'},
      {name: 'Ho Chi Minh City', code: 'VN'},
      {name: 'Da Nang', code: 'VN'},
      {name: 'Haiphong', code: 'VN'},
      {name: 'Binh Duong', code: 'VN'},
    ];

    const states: State[] = [];
    for (const row of rows) {
      const country = byCode.get(row.code);
      if (!country) continue;

      states.push(
        stateRepo.create({
          name: row.name,
          countryId: country.id,
        }),
      );
    }

    await stateRepo.save(states);
    console.log(`✅ Seeded ${states.length} states successfully.`);
  }
}
